// frontend/src/workbench/views/GraphView.tsx
//
// V1.5.2 P3 — graph workbench view. Moved from
// `lineage/GraphWorkbench.tsx` per plan §2.
//
// SCOPE NOTE: P3 keeps GraphView self-contained (it still owns
// DetailDrawer, RawJsonModal, RunHistoryRail, expandedGroups, layout,
// legacy-hint dismissal) to keep the surface compatible with existing
// V1.5.0/1.5.1 tests. Plan §2's full decomposition — rail / drawer /
// bottom panel hoisted to WorkbenchRouteContainer — lands in P4/P5
// once the action + panel registries are actually wired.
//
// Today's contract:
//   - consumes `useLineage()` (back-compat with V1.5.0/1.5.1)
//   - exposes `data-testid="graph-workbench"` (back-compat) +
//     `data-testid="graph-view"` (new canonical id)
//   - `model.legacy` shows LegacyBanner only — no canvas
//
// V1.5.2 P4 will migrate this to `useWorkbench()` for selection/focus
// once the action registry's `selectByCanvasClick` is wired.

import { useEffect, useMemo, useState } from "react";
import { GraphCanvas } from "../../lineage/graph/GraphCanvas";
import { useLayoutMode } from "../../lineage/graph/useLayoutMode";
import { useLineage } from "../../lineage/LineageContext";
import { useGraphKeyboard } from "../../lineage/hooks/useGraphKeyboard";
import { DetailDrawer } from "../../lineage/detail/DetailDrawer";
import { RawJsonModal } from "../../lineage/modals/RawJsonModal";
import { RunHistoryRail } from "../../lineage/runRail/RunHistoryRail";
import { useWorkbenchOptional } from "../WorkbenchStateProvider";

export function GraphView() {
  const { model, selectedKey, select } = useLineage();
  // useWorkbenchOptional() lets GraphView work both inside the new
  // WorkbenchRouteContainer (P3) and inside V1.5.0/1.5.1 test
  // harnesses that mount it bare. When the provider is absent, the
  // context menu hook is simply a no-op.
  const wb = useWorkbenchOptional();
  const [expandedGroups, setExpandedGroups] = useState<Set<string>>(new Set());
  const [rawJsonOpen, setRawJsonOpen] = useState(false);
  // V1.5.1 T4' — per-run sessionStorage-backed layout choice.
  const { layout, setLayout } = useLayoutMode(model.runId);

  // T6.12 legacy stage hint. ≥50% of nodes have stage="unknown" means
  // the graph was generated by a backend that pre-dates V1.5.0 schema v3.
  // Dismissible per browser session; persisted in sessionStorage keyed
  // by runId. Uses the legacy `lineage:` namespace (NOT `workbench:`)
  // for back-compat with sessions opened on V1.5.1.
  const dismissalKey = `lineage:legacy-hint-dismissed:${model.runId}`;
  const [legacyHintDismissed, setLegacyHintDismissed] = useState<boolean>(
    () => {
      try {
        return sessionStorage.getItem(dismissalKey) === "1";
      } catch {
        return false;
      }
    },
  );
  const dismissLegacyHint = () => {
    setLegacyHintDismissed(true);
    try {
      sessionStorage.setItem(dismissalKey, "1");
    } catch {
      /* fall back to per-mount dismissal */
    }
  };
  const unknownStageRatio = useMemo(() => {
    if (model.nodes.length === 0) return 0;
    const unknown = model.nodes.filter((n) => n.stage === "unknown").length;
    return unknown / model.nodes.length;
  }, [model.nodes]);
  const showLegacyHint = !legacyHintDismissed && unknownStageRatio >= 0.5;

  // Coerce selectedKey to null when it doesn't point at a real node.
  // Covers cross-run URL leak (/runs/A?node=x → /runs/B). [REV-3 #3]
  const nodeIndex = useMemo(
    () => new Map(model.nodes.map((n) => [n.id, n])),
    [model.nodes],
  );
  const effectiveSelectedKey =
    selectedKey !== null && nodeIndex.has(selectedKey) ? selectedKey : null;
  const selectedNode =
    effectiveSelectedKey !== null
      ? (nodeIndex.get(effectiveSelectedKey) ?? null)
      : null;

  // REV-3 H1: external selection clear must close the modal.
  useEffect(() => {
    if (selectedNode === null && rawJsonOpen) setRawJsonOpen(false);
  }, [selectedNode, rawJsonOpen]);

  useGraphKeyboard({
    onToggleRawJson: () => {
      if (selectedNode === null) return;
      setRawJsonOpen((v) => !v);
    },
    onEscape: () => {
      // REV-3 S1: modal owns its own Escape; skip when modal open.
      if (rawJsonOpen) return;
      select(null);
    },
    onCmdK: () => {
      /* parent search palette — wired in V1.5.x */
    },
  });

  const handleExpandGroup = (gid: string) => {
    setExpandedGroups((s) => {
      const next = new Set(s);
      if (next.has(gid)) next.delete(gid);
      else next.add(gid);
      return next;
    });
  };

  // V1.4.1 legacy banner — surfaces for pre-V1.4 runs that never
  // recorded lineage. Same copy LineageTab used.
  if (model.legacy) return <LegacyBanner />;

  return (
    <div
      className="lineage-root lineage-with-rail"
      data-testid="graph-workbench"
      data-view="graph"
    >
      {/* V1.5.1 T3' — Run history rail (240px). P4 may hoist this to
       * WorkbenchRouteContainer so it's shared across views; in P3 it
       * stays nested to avoid touching every existing test. */}
      <RunHistoryRail />
      <div className="lineage-with-rail__main">
        {showLegacyHint && <LegacyStageHint onDismiss={dismissLegacyHint} />}
        <div style={{ display: "flex", gap: 0, flex: 1, minHeight: 0 }}>
          <div style={{ flex: 1 }}>
            <GraphCanvas
              model={model}
              selectedNodeId={effectiveSelectedKey}
              expandedGroups={expandedGroups}
              onSelect={select}
              onExpandGroup={handleExpandGroup}
              layout={layout}
              onLayoutChange={setLayout}
              onNodeContextMenu={
                wb
                  ? (nodeId, x, y) =>
                      wb.dispatch.openContextMenu({ nodeKey: nodeId, x, y })
                  : undefined
              }
            />
          </div>
          {selectedNode !== null && (
            <DetailDrawer
              node={selectedNode}
              onClose={() => select(null)}
              onShowJson={() => setRawJsonOpen(true)}
            />
          )}
        </div>
      </div>
      <RawJsonModal
        open={rawJsonOpen}
        onClose={() => setRawJsonOpen(false)}
        node={selectedNode}
      />
    </div>
  );
}

function LegacyStageHint({ onDismiss }: { onDismiss: () => void }) {
  return (
    <div
      role="status"
      aria-live="polite"
      data-testid="legacy-stage-hint"
      style={{
        display: "flex",
        alignItems: "center",
        gap: 12,
        padding: "8px 14px",
        background: "var(--orange-bg)",
        borderBottom: "1px solid var(--separator)",
        fontSize: 12,
        color: "var(--label-secondary)",
      }}
    >
      <span>
        This run predates stage tagging. Re-run to populate stages.
      </span>
      <button
        type="button"
        onClick={onDismiss}
        aria-label="Dismiss legacy stage hint"
        style={{
          marginLeft: "auto",
          border: 0,
          background: "transparent",
          color: "var(--label-tertiary)",
          cursor: "pointer",
          fontSize: 12,
          padding: "2px 6px",
        }}
      >
        Dismiss
      </button>
    </div>
  );
}

function LegacyBanner() {
  return (
    <div
      className="lineage-root"
      style={{
        padding: 24,
        textAlign: "center",
        color: "var(--label-secondary)",
      }}
      data-testid="legacy-banner"
    >
      <div style={{ fontSize: 16, color: "var(--label)", marginBottom: 8 }}>
        No lineage data for this run
      </div>
      <div>
        This run predates V1.4. Lineage tracking became available with V1.4.0.
      </div>
    </div>
  );
}
