// frontend/src/lineage/GraphWorkbench.tsx
//
// V1.5.0 lineage workbench (Step 5, T5.6 + Step 6, T6.11).
//
// Mounts GraphCanvas inside the LineageContext consumer. When a node is
// selected, the right rail mounts DetailDrawer (Step 6, T6.11 swap from
// the T5.6 DrawerSlot placeholder). RawJsonModal is mounted at workbench
// root and controlled by ⌘J via useGraphKeyboard.
//
// expandedGroups state lives here (not in the container) because it is
// graph-render local — V1.5.1 may persist it to URL or context, but
// today it's transient component state.

import { useEffect, useMemo, useState } from "react";
import { GraphCanvas } from "./graph/GraphCanvas";
import { useLayoutMode } from "./graph/useLayoutMode";
import { useLineage } from "./LineageContext";
import { useGraphKeyboard } from "./hooks/useGraphKeyboard";
import { DetailDrawer } from "./detail/DetailDrawer";
import { RawJsonModal } from "./modals/RawJsonModal";

export function GraphWorkbench() {
  const { model, selectedKey, select } = useLineage();
  const [expandedGroups, setExpandedGroups] = useState<Set<string>>(new Set());
  const [rawJsonOpen, setRawJsonOpen] = useState(false);
  // V1.5.1 T4' — per-run sessionStorage-backed layout choice.
  const { layout, setLayout } = useLayoutMode(model.runId);
  // T6.12: legacy stage hint. ≥50% of nodes have stage="unknown" means
  // the graph was generated by a backend that pre-dates V1.5.0 schema v3.
  // Dismissible per browser session (spec §19.4): persisted in
  // sessionStorage keyed by runId so leaving the Lineage tab and coming
  // back does not resurrect the banner within the same session. Cleared
  // automatically when the tab/window closes — no manual reset needed.
  // [REV-3 P2 — Step 6 adversarial review]
  const dismissalKey = `lineage:legacy-hint-dismissed:${model.runId}`;
  const [legacyHintDismissed, setLegacyHintDismissed] = useState<boolean>(
    () => {
      try {
        return sessionStorage.getItem(dismissalKey) === "1";
      } catch {
        // sessionStorage unavailable (e.g. privacy mode) — fall back to
        // per-mount dismissal rather than throwing.
        return false;
      }
    },
  );
  const dismissLegacyHint = () => {
    setLegacyHintDismissed(true);
    try {
      sessionStorage.setItem(dismissalKey, "1");
    } catch {
      /* fall back to per-mount dismissal */
    }
  };
  const unknownStageRatio = useMemo(() => {
    if (model.nodes.length === 0) return 0;
    const unknown = model.nodes.filter((n) => n.stage === "unknown").length;
    return unknown / model.nodes.length;
  }, [model.nodes]);
  const showLegacyHint = !legacyHintDismissed && unknownStageRatio >= 0.5;

  // Coerce selectedKey to null when it doesn't point at a real node in the
  // current model. Covers cross-run URL leak (/runs/A?node=x → /runs/B
  // would otherwise mount an orphan drawer) and any other stale URL state.
  // [REV-3 #3 — Step 5 adversarial review]
  const nodeIndex = useMemo(
    () => new Map(model.nodes.map((n) => [n.id, n])),
    [model.nodes],
  );
  const effectiveSelectedKey =
    selectedKey !== null && nodeIndex.has(selectedKey) ? selectedKey : null;
  const selectedNode =
    effectiveSelectedKey !== null
      ? (nodeIndex.get(effectiveSelectedKey) ?? null)
      : null;

  // REV-3 H1: when selectedNode becomes null externally (URL change,
  // cross-run nav), the modal must close — otherwise rawJsonOpen stays
  // true while the modal renders null body, and the next ⌘J appears to
  // do nothing (it's actually toggling a hidden modal). Worse: if a
  // node selection comes back, the modal pops open unexpectedly.
  useEffect(() => {
    if (selectedNode === null && rawJsonOpen) setRawJsonOpen(false);
  }, [selectedNode, rawJsonOpen]);

  useGraphKeyboard({
    onToggleRawJson: () => {
      // No-op when there's no node to inspect.
      if (selectedNode === null) return;
      setRawJsonOpen((v) => !v);
    },
    onEscape: () => {
      // REV-3 S1: skip when the modal is open. The modal owns its own
      // Escape handler; if we let this fire too, we'd clear node
      // selection underneath the modal and dismount the drawer.
      // (Relying on stopImmediatePropagation in the modal isn't enough
      //  because the two listeners are on the same `window` target —
      //  stopPropagation between same-target listeners is unreliable.)
      if (rawJsonOpen) return;
      select(null);
    },
    onCmdK: () => {
      /* parent search palette — wired in V1.5.x */
    },
  });

  const handleExpandGroup = (gid: string) => {
    setExpandedGroups((s) => {
      const next = new Set(s);
      if (next.has(gid)) next.delete(gid);
      else next.add(gid);
      return next;
    });
  };

  // V1.4.1 legacy banner — model.legacy is true for pre-V1.4 runs that
  // never recorded lineage. Surface the same copy LineageTab used.
  if (model.legacy) return <LegacyBanner />;

  return (
    <div
      className="lineage-root"
      style={{ display: "flex", flexDirection: "column", minHeight: 600 }}
      data-testid="graph-workbench"
    >
      {showLegacyHint && (
        <LegacyStageHint onDismiss={dismissLegacyHint} />
      )}
      <div style={{ display: "flex", gap: 0, flex: 1, minHeight: 0 }}>
        <div style={{ flex: 1 }}>
          <GraphCanvas
            model={model}
            selectedNodeId={effectiveSelectedKey}
            expandedGroups={expandedGroups}
            onSelect={select}
            onExpandGroup={handleExpandGroup}
            layout={layout}
            onLayoutChange={setLayout}
          />
        </div>
        {selectedNode !== null && (
          <DetailDrawer
            node={selectedNode}
            onClose={() => select(null)}
            onShowJson={() => setRawJsonOpen(true)}
          />
        )}
      </div>
      <RawJsonModal
        open={rawJsonOpen}
        onClose={() => setRawJsonOpen(false)}
        node={selectedNode}
      />
    </div>
  );
}

function LegacyStageHint({ onDismiss }: { onDismiss: () => void }) {
  return (
    <div
      role="status"
      aria-live="polite"
      data-testid="legacy-stage-hint"
      style={{
        display: "flex",
        alignItems: "center",
        gap: 12,
        padding: "8px 14px",
        background: "var(--orange-bg)",
        borderBottom: "1px solid var(--separator)",
        fontSize: 12,
        color: "var(--label-secondary)",
      }}
    >
      <span>
        This run predates stage tagging. Re-run to populate stages.
      </span>
      <button
        type="button"
        onClick={onDismiss}
        aria-label="Dismiss legacy stage hint"
        style={{
          marginLeft: "auto",
          border: 0,
          background: "transparent",
          color: "var(--label-tertiary)",
          cursor: "pointer",
          fontSize: 12,
          padding: "2px 6px",
        }}
      >
        Dismiss
      </button>
    </div>
  );
}

function LegacyBanner() {
  return (
    <div
      className="lineage-root"
      style={{
        padding: 24,
        textAlign: "center",
        color: "var(--label-secondary)",
      }}
      data-testid="legacy-banner"
    >
      <div style={{ fontSize: 16, color: "var(--label)", marginBottom: 8 }}>
        No lineage data for this run
      </div>
      <div>
        This run predates V1.4. Lineage tracking became available with V1.4.0.
      </div>
    </div>
  );
}
