"""Deterministic contracts for the Agent Analysis Loop."""

from .canonical import (
    CanonicalJSONError,
    canonical_json_v1,
    numeric_equal,
    numbers_equal,
    sha256_canonical,
)
from .contracts import (
    ClusterPreflightResult,
    ComparePayload,
    ComparisonTarget,
    IntentValidationResult,
    PacketConflictError,
    PacketEnvelope,
    ProposalRejection,
    SourceRunContract,
    SourceValidationResult,
    ensure_packet_idempotent,
)
from .fingerprints import (
    analysis_sample_fingerprint,
    coefficient_schema_fingerprint,
    dataset_snapshot_fingerprint,
    inference_config_fingerprint,
    point_estimation_fingerprint,
)
from .policy import OLS_CLUSTER_POLICY_V1, ols_cluster_policy_v1
from .plan import (
    ACTION_ID,
    PLAN_DIFF_SCHEMA_VERSION,
    PLAN_STRATEGY_VERSION,
    PlanBindingError,
    PlanDiff,
    PlanValidationError,
    build_plan_diff,
    canonicalize_intent,
    confirmed_payload_hash,
    confirmed_payload_hash_for_plan,
    validate_confirmation_binding,
)
from .preflight import (
    preflight_cluster_variable,
    resolve_comparison_target,
    validate_clustered_intent,
    validate_source_contract,
)
from .recovery import (
    OLS_CLUSTERED_RECOVERY_ACTION,
    RECOVERY_ACTION_REGISTRY,
    RECOVERY_ACTIONS,
    RecoveryAction,
    RecoveryActionRegistry,
    get_recovery_action,
)

__all__ = [
    "CanonicalJSONError",
    "ACTION_ID",
    "ClusterPreflightResult",
    "ComparePayload",
    "ComparisonTarget",
    "IntentValidationResult",
    "OLS_CLUSTER_POLICY_V1",
    "OLS_CLUSTERED_RECOVERY_ACTION",
    "PacketConflictError",
    "PacketEnvelope",
    "PLAN_DIFF_SCHEMA_VERSION",
    "PLAN_STRATEGY_VERSION",
    "PlanBindingError",
    "PlanDiff",
    "PlanValidationError",
    "ProposalRejection",
    "RECOVERY_ACTION_REGISTRY",
    "RECOVERY_ACTIONS",
    "RecoveryAction",
    "RecoveryActionRegistry",
    "SourceRunContract",
    "SourceValidationResult",
    "analysis_sample_fingerprint",
    "build_plan_diff",
    "canonicalize_intent",
    "canonical_json_v1",
    "coefficient_schema_fingerprint",
    "confirmed_payload_hash",
    "confirmed_payload_hash_for_plan",
    "dataset_snapshot_fingerprint",
    "ensure_packet_idempotent",
    "inference_config_fingerprint",
    "numbers_equal",
    "numeric_equal",
    "ols_cluster_policy_v1",
    "point_estimation_fingerprint",
    "preflight_cluster_variable",
    "resolve_comparison_target",
    "get_recovery_action",
    "sha256_canonical",
    "validate_clustered_intent",
    "validate_confirmation_binding",
    "validate_source_contract",
]
