"""Provider-neutral browser witness attestation contracts for QA.

The acceptance runner is intentionally not a human-identity authority.  This
module defines the narrow signed-observation protocol that an external witness
provider may implement.  The runner verifies the provider's detached
attestation, but it never mints one and it never treats a local observation
digest as a human proof.  A missing provider is a hard failure.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import hashlib
import importlib
import json
import math
import os
import re
from typing import Any, Literal, Mapping, Protocol


WITNESS_PROTOCOL = "workbench.qa.browser-witness/v1"
WITNESS_SCHEMA_VERSION = 1
WITNESS_CHALLENGE_TTL_SECONDS = 24 * 60 * 60
_SHA256 = re.compile(r"^[0-9a-f]{64}$")
_SAFE_ID = re.compile(r"^[A-Za-z0-9_.:-]+$")


class WitnessError(ValueError):
    """Base class for invalid or unverifiable witness protocol data."""


class WitnessValidationError(WitnessError):
    """The witness envelope is malformed or internally inconsistent."""


class WitnessVerificationError(WitnessError):
    """The witness envelope does not prove the requested frozen binding."""


class WitnessUnavailable(WitnessError):
    """No independent witness verifier was available for the attestation."""


class WitnessVerifier(Protocol):
    """Signature-verifier boundary owned by a witness provider adapter."""

    def verify(self, *, key_id: str, payload: bytes, signature: str) -> bool:
        """Return true only when the provider's detached signature is valid."""


TrustLevel = Literal[
    "none",
    "coordinator_only",
    "witness_attested",
    "human_identity_verified",
]


def _canonical_json(value: object) -> bytes:
    return (
        json.dumps(
            value,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
            allow_nan=False,
        )
        + "\n"
    ).encode("utf-8")


def _digest(value: object) -> str:
    return hashlib.sha256(_canonical_json(value)).hexdigest()


def _required_text(value: object, label: str) -> str:
    if not isinstance(value, str) or not value:
        raise WitnessValidationError(f"{label} must be non-empty text")
    return value


def _safe_id(value: object, label: str) -> str:
    text = _required_text(value, label)
    if _SAFE_ID.fullmatch(text) is None:
        raise WitnessValidationError(f"{label} is not a safe identifier")
    return text


def _sha256_text(value: object, label: str) -> str:
    text = _required_text(value, label).casefold()
    if _SHA256.fullmatch(text) is None:
        raise WitnessValidationError(f"{label} is not a SHA-256 digest")
    return text


def _positive_int(value: object, label: str) -> int:
    if type(value) is not int or value <= 0:
        raise WitnessValidationError(f"{label} must be a positive integer")
    return value


def _finite_time(value: object, label: str) -> float:
    if type(value) not in {int, float} or not math.isfinite(float(value)):
        raise WitnessValidationError(f"{label} must be a finite number")
    if float(value) < 0:
        raise WitnessValidationError(f"{label} must be non-negative")
    return float(value)


def _timestamp(value: object, label: str) -> float:
    text = _required_text(value, label)
    try:
        parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
    except ValueError as error:
        raise WitnessValidationError(f"{label} is not ISO-8601") from error
    if parsed.tzinfo is None:
        raise WitnessValidationError(f"{label} must include a timezone")
    return parsed.astimezone(timezone.utc).timestamp()


def _strict_mapping(value: object, label: str, expected: set[str]) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise WitnessValidationError(f"{label} must be an object")
    actual = set(value)
    if actual != expected:
        missing = sorted(expected - actual)
        extra = sorted(actual - expected)
        detail = []
        if missing:
            detail.append("missing " + ", ".join(missing))
        if extra:
            detail.append("unknown " + ", ".join(extra))
        raise WitnessValidationError(f"{label} fields are incomplete: {'; '.join(detail)}")
    return value


@dataclass(frozen=True)
class WitnessChallenge:
    """Deterministic, one-submission challenge generated by the coordinator."""

    schema_version: int
    protocol: str
    nonce: str
    manifest_digest: str
    submission_id: str
    attempt_no: int
    operation_ids_digest: str
    notebook_id: str
    option_id: str
    option_revision: int
    attempt_started_at: float
    issued_at: float
    expires_at: float
    challenge_digest: str

    @classmethod
    def create(
        cls,
        *,
        manifest_digest: str,
        submission_id: str,
        attempt_no: int,
        operation_ids_digest: str,
        notebook_id: str,
        option_id: str,
        option_revision: int,
        attempt_started_at: float,
        issued_at: float,
        expires_at: float,
    ) -> "WitnessChallenge":
        manifest_digest = _sha256_text(manifest_digest, "manifest_digest")
        operation_ids_digest = _sha256_text(
            operation_ids_digest, "operation_ids_digest"
        )
        submission_id = _safe_id(submission_id, "submission_id")
        notebook_id = _safe_id(notebook_id, "notebook_id")
        option_id = _safe_id(option_id, "option_id")
        attempt_no = _positive_int(attempt_no, "attempt_no")
        option_revision = _positive_int(option_revision, "option_revision")
        attempt_started_at = _finite_time(attempt_started_at, "attempt_started_at")
        issued_at = _finite_time(issued_at, "issued_at")
        expires_at = _finite_time(expires_at, "expires_at")
        if issued_at < attempt_started_at:
            raise WitnessValidationError("issued_at predates attempt_started_at")
        if expires_at <= issued_at:
            raise WitnessValidationError("expires_at must be later than issued_at")
        nonce = _digest(
            {
                "protocol": WITNESS_PROTOCOL,
                "manifest_digest": manifest_digest,
                "submission_id": submission_id,
                "attempt_no": attempt_no,
                "operation_ids_digest": operation_ids_digest,
                "notebook_id": notebook_id,
                "option_id": option_id,
                "option_revision": option_revision,
            }
        )
        unsigned = {
            "schema_version": WITNESS_SCHEMA_VERSION,
            "protocol": WITNESS_PROTOCOL,
            "nonce": nonce,
            "manifest_digest": manifest_digest,
            "submission_id": submission_id,
            "attempt_no": attempt_no,
            "operation_ids_digest": operation_ids_digest,
            "notebook_id": notebook_id,
            "option_id": option_id,
            "option_revision": option_revision,
            "attempt_started_at": attempt_started_at,
            "issued_at": issued_at,
            "expires_at": expires_at,
        }
        return cls(
            **unsigned,
            challenge_digest=_digest(unsigned),
        )

    def _unsigned_dict(self) -> dict[str, object]:
        return {
            "schema_version": self.schema_version,
            "protocol": self.protocol,
            "nonce": self.nonce,
            "manifest_digest": self.manifest_digest,
            "submission_id": self.submission_id,
            "attempt_no": self.attempt_no,
            "operation_ids_digest": self.operation_ids_digest,
            "notebook_id": self.notebook_id,
            "option_id": self.option_id,
            "option_revision": self.option_revision,
            "attempt_started_at": self.attempt_started_at,
            "issued_at": self.issued_at,
            "expires_at": self.expires_at,
        }

    def to_dict(self) -> dict[str, object]:
        return {**self._unsigned_dict(), "challenge_digest": self.challenge_digest}


@dataclass(frozen=True)
class BrowserWitnessAttestation:
    """Detached witness statement for one visible confirmation and result chain."""

    schema_version: int
    protocol: str
    challenge_digest: str
    manifest_digest: str
    submission_id: str
    attempt_no: int
    operation_ids_digest: str
    notebook_id: str
    option_id: str
    option_revision: int
    browser_session_id: str
    confirmation_recorded_at: str
    observed_url: str
    confirmation_control_name: str
    dom_snapshot_sha256: str
    durable_chain_sha256: str
    key_id: str
    signature: str
    attestation_digest: str

    @classmethod
    def create(
        cls,
        *,
        challenge: WitnessChallenge,
        browser_session_id: str,
        confirmation_recorded_at: str,
        observed_url: str,
        confirmation_control_name: str,
        dom_snapshot_sha256: str,
        durable_chain_sha256: str,
        key_id: str,
        signature: str,
    ) -> "BrowserWitnessAttestation":
        if not isinstance(challenge, WitnessChallenge):
            raise WitnessValidationError("a WitnessChallenge is required")
        _validate_challenge(challenge)
        confirmation_recorded_at = _required_text(
            confirmation_recorded_at, "confirmation_recorded_at"
        )
        _timestamp(confirmation_recorded_at, "confirmation_recorded_at")
        confirmation_control_name = _required_text(
            confirmation_control_name, "confirmation_control_name"
        )
        if "confirm" not in confirmation_control_name.casefold() and "确认" not in (
            confirmation_control_name
        ):
            raise WitnessValidationError(
                "confirmation_control_name must identify a visible confirm action"
            )
        unsigned = {
            "schema_version": WITNESS_SCHEMA_VERSION,
            "protocol": WITNESS_PROTOCOL,
            "challenge_digest": challenge.challenge_digest,
            "manifest_digest": challenge.manifest_digest,
            "submission_id": challenge.submission_id,
            "attempt_no": challenge.attempt_no,
            "operation_ids_digest": challenge.operation_ids_digest,
            "notebook_id": challenge.notebook_id,
            "option_id": challenge.option_id,
            "option_revision": challenge.option_revision,
            "browser_session_id": _safe_id(
                browser_session_id, "browser_session_id"
            ),
            "confirmation_recorded_at": confirmation_recorded_at,
            "observed_url": _required_text(observed_url, "observed_url"),
            "confirmation_control_name": confirmation_control_name,
            "dom_snapshot_sha256": _sha256_text(
                dom_snapshot_sha256, "dom_snapshot_sha256"
            ),
            "durable_chain_sha256": _sha256_text(
                durable_chain_sha256, "durable_chain_sha256"
            ),
            "key_id": _safe_id(key_id, "key_id"),
        }
        signature = _required_text(signature, "signature")
        return cls(
            **unsigned,
            signature=signature,
            attestation_digest=_digest(
                {"payload": unsigned, "signature": signature}
            ),
        )

    def _unsigned_dict(self) -> dict[str, object]:
        return {
            "schema_version": self.schema_version,
            "protocol": self.protocol,
            "challenge_digest": self.challenge_digest,
            "manifest_digest": self.manifest_digest,
            "submission_id": self.submission_id,
            "attempt_no": self.attempt_no,
            "operation_ids_digest": self.operation_ids_digest,
            "notebook_id": self.notebook_id,
            "option_id": self.option_id,
            "option_revision": self.option_revision,
            "browser_session_id": self.browser_session_id,
            "confirmation_recorded_at": self.confirmation_recorded_at,
            "observed_url": self.observed_url,
            "confirmation_control_name": self.confirmation_control_name,
            "dom_snapshot_sha256": self.dom_snapshot_sha256,
            "durable_chain_sha256": self.durable_chain_sha256,
            "key_id": self.key_id,
        }

    def signing_payload(self) -> bytes:
        """Return the exact detached-signature payload; never signs caller extras."""

        return _canonical_json(self._unsigned_dict())

    def to_dict(self) -> dict[str, object]:
        return {
            **self._unsigned_dict(),
            "signature": self.signature,
            "attestation_digest": self.attestation_digest,
        }

    @classmethod
    def from_mapping(cls, value: object) -> "BrowserWitnessAttestation":
        expected = {
            "schema_version",
            "protocol",
            "challenge_digest",
            "manifest_digest",
            "submission_id",
            "attempt_no",
            "operation_ids_digest",
            "notebook_id",
            "option_id",
            "option_revision",
            "browser_session_id",
            "confirmation_recorded_at",
            "observed_url",
            "confirmation_control_name",
            "dom_snapshot_sha256",
            "durable_chain_sha256",
            "key_id",
            "signature",
            "attestation_digest",
        }
        data = _strict_mapping(value, "browser witness attestation", expected)
        try:
            attestation = cls(
                schema_version=data["schema_version"],
                protocol=data["protocol"],
                challenge_digest=data["challenge_digest"],
                manifest_digest=data["manifest_digest"],
                submission_id=data["submission_id"],
                attempt_no=data["attempt_no"],
                operation_ids_digest=data["operation_ids_digest"],
                notebook_id=data["notebook_id"],
                option_id=data["option_id"],
                option_revision=data["option_revision"],
                browser_session_id=data["browser_session_id"],
                confirmation_recorded_at=data["confirmation_recorded_at"],
                observed_url=data["observed_url"],
                confirmation_control_name=data["confirmation_control_name"],
                dom_snapshot_sha256=data["dom_snapshot_sha256"],
                durable_chain_sha256=data["durable_chain_sha256"],
                key_id=data["key_id"],
                signature=data["signature"],
                attestation_digest=data["attestation_digest"],
            )
        except (TypeError, ValueError) as error:
            raise WitnessValidationError(
                "browser witness attestation has invalid field types"
            ) from error
        _validate_attestation_shape(attestation)
        expected_digest = _digest(
            {
                "payload": attestation._unsigned_dict(),
                "signature": attestation.signature,
            }
        )
        if attestation.attestation_digest != expected_digest:
            raise WitnessValidationError("browser witness attestation digest is invalid")
        return attestation


@dataclass(frozen=True)
class WitnessVerification:
    """Result of witness verification, deliberately below human identity proof."""

    attestation_digest: str
    key_id: str
    trust_level: TrustLevel
    human_identity_verified: bool = False


def _validate_challenge(challenge: WitnessChallenge) -> None:
    if challenge.schema_version != WITNESS_SCHEMA_VERSION:
        raise WitnessValidationError("witness challenge schema drifted")
    if challenge.protocol != WITNESS_PROTOCOL:
        raise WitnessValidationError("witness challenge protocol drifted")
    expected = WitnessChallenge.create(
        manifest_digest=challenge.manifest_digest,
        submission_id=challenge.submission_id,
        attempt_no=challenge.attempt_no,
        operation_ids_digest=challenge.operation_ids_digest,
        notebook_id=challenge.notebook_id,
        option_id=challenge.option_id,
        option_revision=challenge.option_revision,
        attempt_started_at=challenge.attempt_started_at,
        issued_at=challenge.issued_at,
        expires_at=challenge.expires_at,
    )
    if challenge.to_dict() != expected.to_dict():
        raise WitnessValidationError("witness challenge digest or payload is invalid")


def _validate_attestation_shape(attestation: BrowserWitnessAttestation) -> None:
    if attestation.schema_version != WITNESS_SCHEMA_VERSION:
        raise WitnessValidationError("browser witness attestation schema drifted")
    if attestation.protocol != WITNESS_PROTOCOL:
        raise WitnessValidationError("browser witness attestation protocol drifted")
    _sha256_text(attestation.challenge_digest, "challenge_digest")
    _sha256_text(attestation.manifest_digest, "manifest_digest")
    _sha256_text(attestation.operation_ids_digest, "operation_ids_digest")
    _sha256_text(attestation.dom_snapshot_sha256, "dom_snapshot_sha256")
    _sha256_text(attestation.durable_chain_sha256, "durable_chain_sha256")
    _safe_id(attestation.submission_id, "submission_id")
    _safe_id(attestation.notebook_id, "notebook_id")
    _safe_id(attestation.option_id, "option_id")
    _safe_id(attestation.browser_session_id, "browser_session_id")
    _safe_id(attestation.key_id, "key_id")
    _positive_int(attestation.attempt_no, "attempt_no")
    _positive_int(attestation.option_revision, "option_revision")
    _required_text(attestation.signature, "signature")
    _required_text(attestation.observed_url, "observed_url")
    _required_text(attestation.confirmation_control_name, "confirmation_control_name")
    if "confirm" not in attestation.confirmation_control_name.casefold() and "确认" not in (
        attestation.confirmation_control_name
    ):
        raise WitnessValidationError(
            "confirmation_control_name must identify a visible confirm action"
        )
    _timestamp(attestation.confirmation_recorded_at, "confirmation_recorded_at")


def verify_witness_attestation(
    challenge: WitnessChallenge,
    attestation: BrowserWitnessAttestation | Mapping[str, object],
    *,
    verifier: WitnessVerifier | None,
    now: float,
    expected_durable_chain_sha256: str,
) -> WitnessVerification:
    """Verify one provider attestation against one immutable acceptance challenge."""

    _validate_challenge(challenge)
    if isinstance(attestation, Mapping):
        attestation = BrowserWitnessAttestation.from_mapping(attestation)
    if not isinstance(attestation, BrowserWitnessAttestation):
        raise WitnessValidationError("a browser witness attestation is required")
    _validate_attestation_shape(attestation)
    if attestation.challenge_digest != challenge.challenge_digest:
        raise WitnessVerificationError("witness challenge digest does not match")
    for field_name in (
        "manifest_digest",
        "submission_id",
        "attempt_no",
        "operation_ids_digest",
        "notebook_id",
        "option_id",
        "option_revision",
    ):
        if getattr(attestation, field_name) != getattr(challenge, field_name):
            raise WitnessVerificationError(
                f"witness {field_name} does not match the frozen submission"
            )
    expected_chain = _sha256_text(
        expected_durable_chain_sha256, "expected_durable_chain_sha256"
    )
    if attestation.durable_chain_sha256 != expected_chain:
        raise WitnessVerificationError(
            "witness durable result chain does not match the collected chain"
        )
    confirmation_at = _timestamp(
        attestation.confirmation_recorded_at, "confirmation_recorded_at"
    )
    current = _finite_time(now, "now")
    if current >= challenge.expires_at:
        raise WitnessVerificationError("witness challenge is expired")
    if confirmation_at < challenge.attempt_started_at:
        raise WitnessVerificationError(
            "witness confirmation predates the active submission"
        )
    if confirmation_at > current:
        raise WitnessVerificationError("witness confirmation is in the future")
    expected_digest = _digest(
        {"payload": attestation._unsigned_dict(), "signature": attestation.signature}
    )
    if attestation.attestation_digest != expected_digest:
        raise WitnessVerificationError("witness attestation digest is invalid")
    if verifier is None:
        raise WitnessUnavailable("an independent witness verifier is not configured")
    try:
        valid = verifier.verify(
            key_id=attestation.key_id,
            payload=attestation.signing_payload(),
            signature=attestation.signature,
        )
    except Exception as error:  # noqa: BLE001 - provider failures remain fail-closed.
        raise WitnessUnavailable("independent witness verifier failed") from error
    if valid is not True:
        raise WitnessVerificationError("witness signature is invalid")
    identity_verified = getattr(verifier, "human_identity_verified", False)
    if type(identity_verified) is not bool:
        raise WitnessUnavailable("witness provider identity decision is invalid")
    return WitnessVerification(
        attestation_digest=attestation.attestation_digest,
        key_id=attestation.key_id,
        trust_level=(
            "human_identity_verified"
            if identity_verified
            else "witness_attested"
        ),
        human_identity_verified=identity_verified,
    )


def load_witness_verifier(spec: str | None) -> WitnessVerifier | None:
    """Load an explicitly selected trusted provider adapter.

    The default is no provider, which is intentionally unusable for
    witness-attested completion.  When the complete remote provider
    configuration is present, it is selected explicitly by that configuration
    even if the CLI spec is omitted.  The adapter spec is an operator-controlled
    ``module:factory`` reference; it is a provider integration seam, not a
    claim that local module loading establishes human identity.
    """

    if spec is None:
        generic_configured = any(
            os.environ.get(name) is not None
            for name in (
                "WORKBENCH_WITNESS_PROVIDER_URL",
                "WORKBENCH_WITNESS_PROVIDER_ID",
                "WORKBENCH_WITNESS_PROVIDER_TOKEN",
                "WORKBENCH_WITNESS_PROVIDER_TIMEOUT_SECONDS",
            )
        )
        if generic_configured:
            from workbench.qa.remote_witness import from_environment

            return from_environment()
        return None
    if not isinstance(spec, str) or spec.count(":") != 1:
        raise WitnessUnavailable(
            "witness provider must use an explicit module:factory spec"
        )
    module_name, factory_name = spec.split(":", 1)
    if not module_name or not factory_name or not _SAFE_ID.fullmatch(
        factory_name
    ):
        raise WitnessUnavailable("witness provider spec is invalid")
    try:
        factory = getattr(importlib.import_module(module_name), factory_name)
        verifier = factory() if callable(factory) else factory
    except Exception as error:  # noqa: BLE001 - provider load is fail-closed.
        raise WitnessUnavailable("witness provider could not be loaded") from error
    if not callable(getattr(verifier, "verify", None)):
        raise WitnessUnavailable("witness provider has no callable verify method")
    return verifier


__all__ = [
    "BrowserWitnessAttestation",
    "TrustLevel",
    "WitnessChallenge",
    "WitnessError",
    "WitnessUnavailable",
    "WitnessValidationError",
    "WitnessVerification",
    "WitnessVerificationError",
    "WitnessVerifier",
    "WITNESS_PROTOCOL",
    "WITNESS_SCHEMA_VERSION",
    "WITNESS_CHALLENGE_TTL_SECONDS",
    "load_witness_verifier",
    "verify_witness_attestation",
]
