"""Known-truth recovery for the v1.8.1 ETS pack.

Every assertion is a concrete number. The series are generated by
`tests/fixtures/models/ets/known_truth.py`, which implements the ETS
innovations recursions by hand and never calls the production pack or
statsmodels, so recovery here is a real oracle.

Tolerance policy (stated once, applied below):

* n = 4000 for every recovery fixture. The asymptotic standard errors reported
  by the fitted model at that length are ~0.013 for `smoothing_level`, ~0.0045
  for `smoothing_trend`, ~0.013 for `damping_trend` and ~0.008 for
  `smoothing_seasonal`. Each tolerance below is set to roughly three of those
  standard errors and rounded up to a readable number, i.e. a genuine
  three-sigma statement about MLE sampling error, not a number widened until
  the test passed.
* sigma^2 has asymptotic standard error sigma^2 * sqrt(2/n) = 0.0224 at
  n = 4000; the tolerance is 0.07 (~3 sigma).
"""

from __future__ import annotations

import math

from tests.fixtures.models.ets.known_truth import (
    additive_trend_series,
    damped_trend_series,
    seasonal_series,
)
from workbench.contracts.model.ets import ETS_MODEL_TYPE, ETSResultContract
from workbench.engine.packs.ets.runner import fit_ets


ALPHA_TOLERANCE = 0.04
BETA_TOLERANCE = 0.015
GAMMA_TOLERANCE = 0.03
PHI_TOLERANCE = 0.04
SIGMA2_TOLERANCE = 0.07


def _fit(series, **specification):
    frame = series.frame()
    return fit_ets(
        frame,
        {
            "time_column": "date",
            "value_column": "y",
            "error": "add",
            **specification,
        },
    )


def test_additive_trend_recovers_known_parameters() -> None:
    series = additive_trend_series()
    outcome = _fit(series, trend="add", seasonal=None, damped_trend=False)
    result = outcome.result

    assert isinstance(result, ETSResultContract)
    assert result.model_type == ETS_MODEL_TYPE
    assert result.specification.canonical == "ETS(A,A,N)"
    assert result.convergence_code == "converged"
    assert result.n_obs == 4_000
    assert result.n_excluded == 0

    assert abs(result.params["smoothing_level"] - 0.40) <= ALPHA_TOLERANCE
    assert abs(result.params["smoothing_trend"] - 0.10) <= BETA_TOLERANCE
    assert abs(result.sigma2 - 1.0) <= SIGMA2_TOLERANCE
    assert math.isfinite(result.aic) and math.isfinite(result.bic)
    assert result.bic > result.aic


def test_damped_trend_recovers_known_damping() -> None:
    series = damped_trend_series()
    outcome = _fit(series, trend="add", seasonal=None, damped_trend=True)
    result = outcome.result

    assert result.specification.canonical == "ETS(A,Ad,N)"
    assert result.convergence_code == "converged"
    assert abs(result.params["smoothing_level"] - 0.40) <= ALPHA_TOLERANCE
    assert abs(result.params["smoothing_trend"] - 0.10) <= BETA_TOLERANCE
    assert abs(result.params["damping_trend"] - 0.90) <= PHI_TOLERANCE
    assert abs(result.sigma2 - 1.0) <= SIGMA2_TOLERANCE


def test_seasonal_recovers_known_seasonal_smoothing() -> None:
    series = seasonal_series()
    outcome = _fit(
        series,
        trend="add",
        seasonal="add",
        seasonal_periods=4,
        damped_trend=False,
    )
    result = outcome.result

    assert result.specification.canonical == "ETS(A,A,A)"
    assert result.specification.seasonal_periods == 4
    assert result.convergence_code == "converged"
    assert abs(result.params["smoothing_level"] - 0.40) <= ALPHA_TOLERANCE
    assert abs(result.params["smoothing_trend"] - 0.05) <= BETA_TOLERANCE
    assert abs(result.params["smoothing_seasonal"] - 0.10) <= GAMMA_TOLERANCE
    assert abs(result.sigma2 - 1.0) <= SIGMA2_TOLERANCE


def test_specification_difference_changes_result_identity() -> None:
    series = damped_trend_series()
    undamped = _fit(series, trend="add", seasonal=None, damped_trend=False)
    damped = _fit(series, trend="add", seasonal=None, damped_trend=True)

    assert undamped.result.specification.canonical == "ETS(A,A,N)"
    assert damped.result.specification.canonical == "ETS(A,Ad,N)"
    assert undamped.result.result_identity != damped.result.result_identity
    assert len(undamped.result.result_identity) == 64


def test_result_identity_is_stable_across_refits() -> None:
    series = additive_trend_series()
    first = _fit(series, trend="add", seasonal=None, damped_trend=False)
    second = _fit(series, trend="add", seasonal=None, damped_trend=False)

    assert first.result.result_identity == second.result.result_identity
    assert first.result.aic == second.result.aic


def test_result_never_reports_volatility_fields() -> None:
    series = additive_trend_series()
    outcome = _fit(series, trend="add", seasonal=None, damped_trend=False)
    payload = outcome.result.to_dict()

    forbidden = {"var", "value_at_risk", "conditional_variance", "volatility"}
    assert forbidden & set(payload["params"]) == set()
    assert forbidden & set(payload) == set()
